name: Simple Usage

on: workflow_dispatch

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Convert DOCX to Markdown using Pandoc
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace pandoc/latex:2.9 \
          -f docx -t markdown "黄山徒步路线体力消耗优化模型研究_蒋宇皓.docx" -o foo.markdown
      
      - name: Upload converted Markdown file
        uses: actions/upload-artifact@v2
        with:
          name: converted-markdown
          path: foo.markdown
